kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kafka-bridge
spec:
  host: kafka-bridge-bobbycar.apps.cluster-sing-3f05.sing-3f05.example.opentlc.com
  to:
    kind: Service
    name: bobbycar-bridge-service
    weight: 100
  port:
    targetPort: rest-api
  wildcardPolicy: None
